General code cleanup & added annotations
leaderboardsgg/leaderboard-backend pull request #123
Opened 2022-07-31 00:00 UTC by just-ero

Extends #122.

Addresses some concerns I stumbled upon when adjusting some code to be more readable and performant. A lot of `// FIXME`, `// TODO` and `// NOTE` comments were added that could be discussed in the future.

2022-07-31 00:07 UTC, just-ero commented
All tests pass locally. :/

2022-09-09 18:09 UTC, zysim requested changes
Sorry this took awhile. I'm mostly happy with these changes; just two questions.

2022-09-09 18:29 UTC, just-ero commented on .editorconfig
> +trim_trailing_whitespace = false
I don't remember why I added this. Maybe because of markdown files, which require some trailing spaces?

2022-09-09 18:46 UTC, just-ero commented on LeaderboardBackend/Controllers/LeaderboardsController.cs
> +	/// <response code="404">No `Leaderboard` with the requested ID could be found.</response>
The backticks don't render the text as a code block for these entries:
![image](https://user-images.githubusercontent.com/56401411/189422160-ef6a52b3-8257-4a62-93ec-d7915516c30f.png)

2022-09-10 07:05 UTC, zysim requested changes
Sorry I missed another thing.

2022-09-10 07:05 UTC, zysim commented on LeaderboardBackend/Models/Requests/BanRequests.cs
> +	// NOTE: Should this be [Required]? - Ero
Yeah, this should be Required now, since we've got separate leaderboard ban request and site ban request objects now.

2022-09-10 07:06 UTC, zysim commented on LeaderboardBackend/Controllers/LeaderboardsController.cs
> +	/// <response code="404">No `Leaderboard` with the requested ID could be found.</response>
Ah, I see. Thanks

2022-09-10 07:07 UTC, zysim commented on .editorconfig
> +trim_trailing_whitespace = false
Do Markdown files really need trailing spaces sometimes? Please lemme know if that's true. But yeah ideally I'd like a default `trim_trailing_whitespace = true`, with extension-specific exemptions if we need to.

2022-09-10 07:23 UTC, zysim approved these changes
Aight this is nice. Thanks man.

2022-09-10 07:24 UTC, merged