refactor: split up GET Bans into two separate routes.
leaderboardsgg/leaderboard-backend pull request #92
Opened 2022-05-26 01:39 UTC by JoshDevHub

Refactor of the GET Bans method into two separate routes, one for leaderboard ID and one for user ID. Dropped route for GET all bans.

2022-05-26 01:57 UTC, TemperGrace commented
When this is reviewed/merged, can we initialise a section in the wiki/documentation regarding Moderation, and document this functionality there? This is just one tool amongst what will become an entire toolset - will be important!

2022-05-26 02:03 UTC, RageCage64 commented
The docs for this don't change any documented functionality; the changes that this PR presents will be part of the generated API documentation in the comments.

2022-05-26 14:12 UTC, zysim requested changes
Just a bunch of style changes from me. I'd like for entities to always be referred to in lowercase, e.g. in docs and in response messages. (I should add this to the style guide).

2022-05-26 14:12 UTC, zysim commented on LeaderboardBackend/Controllers/BansController.cs
> +	/// <param name="leaderboardId">Gets Bans a Leaderboard has.</param>
```suggestion
	/// <param name="leaderboardId">The leaderboard ID.</param>
```

2022-05-26 14:12 UTC, zysim commented on LeaderboardBackend/Controllers/BansController.cs
> +			return NotFound("No bans found for this User");
```suggestion
			return NotFound("No bans found for this user");
```

2022-05-27 00:33 UTC, zysim approved these changes

2022-05-27 00:33 UTC, merged

2022-05-27 16:33 UTC, zysim commented
> When this is reviewed/merged, can we initialise a section in the wiki/documentation regarding Moderation, and document this functionality there? This is just one tool amongst what will become an entire toolset - will be important!

While what Rage has said _is_ true, I do see a use for documenting our system for moderation. I could park a WIP page in the wiki for this.